### ISSUE TITLE
[TERM REQUEST]: body_system

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ontology#17]
### What is the term type?

Property

### Describe the new terms

1. <body_system>: <The collection of organs that an individual organ belongs to, e.g., large intestine -> digestive>

### Which category does the list of new terms are related to?

Biological Structure

### Who request these new terms?

Andreas Bueckle (0000-0002-8977-498X)

**Comment by emquardokus** [comment]
Uberon has "anatomical system" Multicellular, connected anatomical structure that has multiple organs as parts and whose parts work together to achieve some shared function. [ http://purl.obolibrary.org/obo/CARO_0000011 ]

**Comment by johardi** [comment]
I agree with Ellen, the definition of "anatomical system" from UBERON fits your "body system" definition.
