### ISSUE TITLE
Make OLS config for CCF ontology

### ISSUE THREAD

**Issue by dosumis** [hubmapconsortium/ccf-ontology#5]
Should have preferred roots specified for all ASCT+B tables.

Example config here https://github.com/EBISPOT/ontotools-docker/blob/master/config/ols-config/ols-config.yaml

Some details of config here https://www.ebi.ac.uk/ols/docs/installation-guide - but out of date.  Check with OLS devs how to spec preferred roots (and ask them to update their doc!).

**Comment by johardi** [comment]
Submitting an ontology to OLS: https://github.com/EBISPOT/OLS/wiki/How-are-ontologies-added-to-OLS%3F

**Comment by johardi** [comment]
Related to issue #13

**Comment by anitacaron** [comment]
The CCF Ontology is on OLS https://www.ebi.ac.uk/ols/ontologies/ccf
